package com.example.androiddata.datamodel

import com.example.androiddata.remote.RemoteRepositoryConstants

/**
 * ATTENTION!
 * Field names need to match the constants in [RemoteRepositoryConstants].
 *
 * @param id Generated by Firebase.
 */
data class FirebaseItem(val title: String,
                        val position: Int,
                        val userListId: String,
                        val id: String = "") {
    /**
     * Required by Firestore.
     */
    constructor() : this("", -1, "", "")
}