name: CI

on:
  pull_request:
    branches: [ master ]
  push:
    branches-ignore: [ master ]

# The CI job is a god job due to a security issue.
# In order to transfer the restored files in-between jobs, I would have to upload and then download them.
# That is a security breach because the uploaded files will be publicly available.

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Restore keystore.properties
      run: |
        echo "${{ secrets.KEYSTORE_PROPERTIES }}" > keystore.properties.asc
        gpg -d --passphrase "${{ secrets.KEYSTORE_PROPERTIES_PASSPHRASE }}" --batch keystore.properties.asc > keystore.properties
    - name: Restore keystore.jsk
      run: |
        echo "${{ secrets.KEYSTORE }}" > lists_keystore.jks.asc
        gpg -d --passphrase "${{ secrets.KEYSTORE_PASSPHRASE }}" --batch lists_keystore.jks.asc > app/lists_keystore.jks
    - name: Restore debug google.json
      run: |
        echo "${{ secrets.GOOGLE_JSON_DEBUG }}" > google-services.json.asc
        gpg -d --passphrase "${{ secrets.GOOGLE_JSON_DEBUG_PASSPHRASE }}" --batch google-services.json.asc > app/src/debug/google-services.json
    - name: Restore release google.json
      run: |
        echo "${{ secrets.GOOGLE_JSON_RELEASE }}" > google-services.json.asc
        gpg -d --passphrase "${{ secrets.GOOGLE_JSON_RELEASE_PASSPHRASE }}" --batch google-services.json.asc > app/src/release/google-services.json
    # Build
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: Build debug APK
      run: ./gradlew buildDebug --info
    # Unit Tests
    - name: Run all unit tests
      run: ./gradlew testDebug --info
      
