package com.example.david.lists.data.datamodel;

import androidx.annotation.NonNull;

/**
 * ATTENTION!
 * Field names need to match the constants in {@link com.example.david.lists.data.remote.RemoteRepositoryConstants}.
 */
public final class Item {

    private String id;
    private String title;
    private int position;

    private String userListId;

    public Item(String title, int position, String userListId) {
        this.title = title;
        this.position = position;
        this.userListId = userListId;
    }

    /**
     * The ID is generated by Firebase, thus it is not known
     * when a Item is first created.
     * @param id Generated by Firebase
     * @param item The previously created Item without an ID
     */
    public Item(String id, Item item) {
        this.id = id;
        this.title = item.title;
        this.position = item.position;
        this.userListId = item.userListId;
    }

    public Item() {
    }


    public String getId() {
        return id;
    }

    public String getTitle() {
        return title;
    }

    public int getPosition() {
        return position;
    }

    public String getUserListId() {
        return userListId;
    }


    @NonNull
    @Override
    public String toString() {
        return id + title + position + userListId;
    }
}
