package com.example.david.lists.data.datamodel;

import androidx.annotation.NonNull;

/**
 * Field names need to match the constants in {@link DataModelFieldConstants}.
 */
public final class UserList {

    private String id;
    private String title;
    private int position;

    public UserList(String title, int position) {
        this.title = title;
        this.position = position;
    }

    /**
     * The ID is generated by Firebase, thus it is not known
     * when a UserList is first created.
     * @param id Generated by Firebase
     * @param userList The previously created UserList without an ID
     */
    public UserList(String id, UserList userList) {
        this.id = id;
        this.title = userList.title;
        this.position = userList.position;
    }

    public UserList() {
    }


    public String getId() {
        return id;
    }

    public String getTitle() {
        return title;
    }

    public int getPosition() {
        return position;
    }


    @NonNull
    @Override
    public String toString() {
        return id + title + position;
    }
}
